---
title: "Data"
author: "Sara"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE,
                      message = FALSE, warning = FALSE, comment = NA,
                      fig.width=8, fig.height=6)
```

```{r}
library(tidyverse)
library(readxl)
library(naniar)
```

```{r}
pseo_co <- read_excel("~/Downloads/pseo_co.xlsx", skip = 4)
cip_info <- read_csv("~/Downloads/label_cipcode.csv")
```

```{r}
pseo <- pseo_co %>% 
  filter(agg_level_pseo == 48, status_y1_earnings == "1", status_y5_earnings == "1", status_y10_earnings == "1")

pseo <- pseo %>% 
  mutate(cipcode_twodigit = str_replace_all(pseo$cipcode, pattern = "\\..*", "")) 
```


```{r}
cip_2d <- cip_info %>% 
  slice(1:48)
pseo <- pseo %>% 
  left_join(cip_2d, by = c("cipcode_twodigit" = "CIPFamily"))
```

```{r}
pseo <- pseo %>% 
  mutate(label = str_replace(label, pattern = "Engineering Technologies and Engineering-Related Fields", replacement = "Engineering"))
```


```{r}
pseo %>% 
  group_by(label) %>% 
  filter(status_y1_earnings == "1", label_degree_level == "Masters", label == "History") %>% 
  select(y1_p50_earnings, y5_p50_earnings, y10_p50_earnings)
  
```

```{r}
test <- pseo %>% 
  group_by(label) %>% 
  filter(status_y1_earnings == "1", status_y5_earnings == "1", status_y10_earnings == "1", 
         degree_level == "05", label == "Engineering") %>% 
  summarise(medy1 =  mean(as.numeric(y1_p50_earnings)),
            medy5 =  mean(as.numeric(y5_p50_earnings)),
            medy10 =  mean(as.numeric(y10_p50_earnings))) 
```

```{r}
plot_data_long <- plot_data_long %>% 
            mutate(Type = factor(Type, levels = c("medy1", "medy5", "medy10")))
```


```{r}
pseo %>% 
  filter(label == "English Language and Literature/Letters") %>% 
  select(label_degree_level, status_y1_earnings, status_y5_earnings, status_y10_earnings) 

pseo %>%
        group_by(label) %>% 
        filter(status_y1_earnings == "1", status_y5_earnings == "1", status_y10_earnings == "1", 
               label_degree_level == "Masters", label == "Engineering") %>% 
  summarise(medy1 =  mean(as.numeric(y1_p50_earnings)),
            medy5 =  mean(as.numeric(y5_p50_earnings)),
            medy10 =  mean(as.numeric(y10_p50_earnings))) 

pseo %>%
        group_by(label) %>% 
        filter(status_y1_earnings == "1", status_y5_earnings == "1", status_y10_earnings == "1",
               label_degree_level == "Masters") %>% 
        summarise(med_y10 = mean(as.numeric(y10_p50_earnings)))  %>% 
        arrange(-med_y10)
  
  nrow(filter(.data = pseo, label == "Foreign Languages, Literatures, and Linguistics", label_degree_level == "Post-Masters Certificate")) == 0
```

```{r}
test <- c("Psychology","Visual and Performing Arts")
new_test <- c("Engineering", test)
new_test <- paste(new_test, collapse = "|")

```

```{r}
plot_data <- pseo %>% 
            group_by(label) %>% 
            filter(status_y1_earnings == "1", status_y5_earnings == "1", status_y10_earnings == "1", 
                   label_degree_level == "Masters", str_detect(label, new_test)) %>% 
            summarise(medy1 =  mean(as.numeric(y1_p50_earnings)),
                      medy5 =  mean(as.numeric(y5_p50_earnings)),
                      medy10 =  mean(as.numeric(y10_p50_earnings))) 
plot_data_long <- plot_data %>% 
    pivot_longer(cols = c(medy1, medy5, medy10), names_to = "Type", values_to = "Amount")
ggplot(plot_data_long, mapping = aes(x = Type, y = Amount, fill = label)) +
            geom_bar(stat = "identity", position = "dodge") +
            scale_y_continuous(limit = c(0, 110000)) + scale_fill_brewer(palette = "Set2")
```

```{r}
pseo %>%
    group_by(label) %>% 
    filter(status_y1_earnings == "1", status_y5_earnings == "1", status_y10_earnings == "1", label == "Engineering") %>% 
  distinct(label_grad_cohort)

#options <- as.character(as_vector(options$label_degree_level))
```


```{r}
pseo %>%
    group_by(label) %>% 
    filter(status_y1_earnings == "1", status_y5_earnings == "1", status_y10_earnings == "1", label == "Engineering", label_grad_cohort == "2001-2005") %>% 
    summarise(medy1 =  mean(as.numeric(y1_p50_earnings)),
            medy5 =  mean(as.numeric(y5_p50_earnings)),
            medy10 =  mean(as.numeric(y10_p50_earnings))) 
  
```



```{r}
pseo %>%
        group_by(label) %>% 
        filter(status_y1_earnings == "1", status_y5_earnings == "1", status_y10_earnings == "1", 
               label_degree_level == "Masters", label == "Engineering" | label == "Psychology")  
```

```{r}
test1 <- "engineering"
test2 <- c("math", "science", "engineering")
test2 <- test2[!test2 %in% test1]
```

```{r}
pseo %>% 
  filter(status_y1_earnings == "1", status_y5_earnings == "1", status_y10_earnings == "1") %>%
  select(label_cipcode,label, label_grad_cohort, label_degree_level, y1_p50_earnings, y5_p50_earnings, y10_p50_earnings)
```


